---
  paths:
    - key: homedir
      value: C:\ValeDataTesting\
  
  dates:
    - key: from
      value: 2020-11-01

    - key: to
      value: 2020-11-29

    - key: yearStartDate
      value: 2020-01-01

  kpiloc:
    - plant: COLEMAN MINE
    - plant: COPPER CLIFF MINE
    - plant: CREIGHTON MINE
    - plant: GARSON MINE
    - plant: OVOID MINE
    - plant: THOMPSON MINE
    - plant: TOTTEN MINE

  dimOMKeys:
    - keynum: 14046
    - keynum: 14048
    - keynum: 14047
    - keynum: 14049
    - keynum: 77580
    - keynum: 77428
    - keynum: 14050
  
  kpiID:
    - id: 1.3
    - id: 1.1
    - id: 1.2
    - id: 185
    - id: 189
    - id: 143